name: Deploy FastAPI to NCP

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

#      - name: Install dependencies locally (for Actions)
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt

      - name: Deploy to NCP Server
        uses: appleboy/ssh-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.NCP_SSH_KEY }}  # GitHub Secret에 SSH Key 등록
          SERVER_USER: ${{ secrets.NCP_SERVER_USER }}
          SERVER_IP: ${{ secrets.NCP_SERVER_IP }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}  # NCP 서버 프로젝트 경로
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          username: ${{ secrets.NCP_SERVER_USER }}
          key: ${{ secrets.NCP_SSH_KEY }}
          port: '22'
          script: |
            whoami